prog_name: repolite
top_dir: ext  # local directory path for enabled repositories
pull_with_rebase: false  # use --ff-only if false
# add new repo_name sections as needed
repos:
  - repo_name: openscap
    repo_alias: oscap
    repo_url: git@github.com:VCTLabs/openscap.git
    repo_depth: 0
    repo_remote: origin
    repo_opts: []
    repo_branch: workbench-1.3
    repo_hash: 1.3.10
    repo_use_rebase: true
    repo_has_lfs_files: false
    repo_init_submodules: false
    repo_install: false
    repo_enable: true
  - repo_name: scap-security-guide
    repo_alias: content
    repo_url: git@github.com:VCTLabs/scap-security-guide.git
    repo_depth: 0
    repo_remote: origin
    repo_opts: []
    repo_branch: oe-stable
    repo_hash: v0.1.74
    repo_use_rebase: true
    repo_has_lfs_files: false
    repo_init_submodules: false
    repo_install: false
    repo_enable: true
  - repo_name: pyserv
    repo_alias: null
    repo_url: https://github.com/sarnold/pyserv.git
    repo_depth: 0
    repo_remote: origin
    repo_opts: []
    repo_branch: master
    repo_hash: 1.6.0
    repo_use_rebase: false
    repo_has_lfs_files: false
    repo_init_submodules: false
    repo_install: false
    repo_enable: true
  - repo_name: ymltoxml
    repo_alias: null
    repo_url: https://github.com/sarnold/ymltoxml.git
    repo_depth: 0
    repo_remote: origin
    repo_opts: []
    repo_branch: main
    repo_hash: null
    repo_use_rebase: false
    repo_has_lfs_files: false
    repo_init_submodules: false
    repo_install: false
    repo_enable: true
